name: license_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  supabase_flutter: ^2.8.4
  responsive_sizer: ^3.3.1
  go_router: ^14.8.1
  file_picker: ^8.0.5
  uuid: ^4.5.1
  firebase_core: ^3.13.0
  googleapis_auth: ^2.0.0
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.2.4
  stream_chat_flutter: ^9.7.0
  stream_video_flutter: ^0.9.1
  stream_video: ^0.9.1
  stream_video_push_notification: ^0.9.1
  stream_video_screen_sharing: ^0.9.1
  cloud_functions: ^5.4.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9 # For SVG
  slide_to_act: ^2.0.2 # For Welcome Page slide button
  get: ^4.6.6 # For State Management And Page routing 
  firebase_auth: ^5.5.2 # For Firebase Authentication
  image_picker: ^1.0.7 # For Image Picker
  firebase_storage: ^12.4.5 # For Firebase Storage
  intl: ^0.19.0 # For Date and time format
  cached_network_image: ^3.3.1 # For Cached Network Image
  fluttertoast: ^8.2.4 # For Toast Message
 # zego_uikit_prebuilt_call: ^4.5.1 # For Video Call
#  zego_uikit_signaling_plugin: ^2.7.6
  flutter_callkit_incoming: ^2.0.1+2

  http: ^1.2.0
  package_info_plus: ^8.2.1
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
