name: license_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.8.1
  provider: ^6.1.4
  responsive_sizer: ^3.3.1
  supabase_flutter: ^2.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
